/*
   ENUM for sub-unit types
*/

#ifndef INCLUDE_GUARD_MASTERHEADERCONSTANTS
#define INCLUDE_GUARD_MASTERHEADERCONSTANTS

// ENUM identifying all the sub-unit types
enum subunittypes{ UNKNOWN, SYMBOLICSUBUNIT, POINT, GAUSSIANPOLYMER, GAUSSIANLOOP, THINCIRCLE, THINROD, THINSPHERICALSHELL,  THINDISK, SOLIDSPHERE, SOLIDSPHERICALSHELL, SOLIDCYLINDER};

#endif
